// import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Toaster } from 'react-hot-toast';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster
          position="top-right"
          containerClassName="manrope size-16"
          toastOptions={{
            duration: 2000,
            style: {
              background: 'white',
              color: 'rgba(200, 169, 107, 1)',
              borderRadius: '8px',
              padding: '10px 16px',
              border:'1px solide rgba(200, 169, 107, 1)'
            },
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
